In [1]:
1 + 2 * 3 

7

In [2]:
2**3

8

In [3]:
x = "Machine" + "Learning"
print(x)

MachineLearning


In [4]:
x.upper()

'MACHINELEARNING'

In [5]:
x.lower()

'machinelearning'

In [6]:
len(x)

15

In [7]:
a = 2 + 3
b = a * 4
c = b - 7
L = [a, b, c]
print(L)

[5, 20, 13]


In [8]:
M = [10, 2, "a", 3.5]
N = L + M
print(N)

[5, 20, 13, 10, 2, 'a', 3.5]


In [9]:
len(N)

7

In [10]:
N[2]

13

In [11]:
N[:3]

[5, 20, 13]

In [12]:
N[3:]

[10, 2, 'a', 3.5]

In [13]:
N[3:6]

[10, 2, 'a']

In [14]:
studentIds = {'knuth': 42.0, 'turing': 56.0, 'nash': 92.0 }
studentIds['turing']

56.0

In [15]:
studentIds['ada'] = 97.0
studentIds

{'knuth': 42.0, 'turing': 56.0, 'nash': 92.0, 'ada': 97.0}

In [16]:
del studentIds['knuth']
studentIds

{'turing': 56.0, 'nash': 92.0, 'ada': 97.0}

In [17]:
studentIds['knuth'] = [42.0, 'forty-two']
studentIds

{'turing': 56.0, 'nash': 92.0, 'ada': 97.0, 'knuth': [42.0, 'forty-two']}

In [18]:
studentIds.keys()

dict_keys(['turing', 'nash', 'ada', 'knuth'])

In [19]:
list(studentIds)

['turing', 'nash', 'ada', 'knuth']

In [20]:
list(studentIds.values())

[56.0, 92.0, 97.0, [42.0, 'forty-two']]

In [21]:
list(studentIds.items())

[('turing', 56.0),
 ('nash', 92.0),
 ('ada', 97.0),
 ('knuth', [42.0, 'forty-two'])]

In [22]:
list(studentIds)

['turing', 'nash', 'ada', 'knuth']

In [23]:
len(studentIds) 

4

In [24]:
fruits = ['apples', 'oranges', 'pears', 'bananas']
for fruit in fruits:
    print (fruit + ' for sale')

apples for sale
oranges for sale
pears for sale
bananas for sale


In [25]:
fruitPrices = {'apples': 2.00, 'oranges': 1.50, 'pears': 1.75}

for fruit, price in fruitPrices.items():
    if price < 2.00:
        print ('%s cost %f a pound' % (fruit, price))
    else:
        print (fruit + ' are too expensive!')

apples are too expensive!
oranges cost 1.500000 a pound
pears cost 1.750000 a pound


In [26]:
nums = [1, 2, 3, 4, 5, 6]
plusOneNums = [x + 1 for x in nums]
print("plusOneNums =", plusOneNums)

oddNums = [x for x in nums if x % 2 == 1]
print("oddNums = ", oddNums) 

oddNumsPlusOne = [x + 1 for x in nums if x % 2 ==1]
print("oddNumsPlusOn = ", oddNumsPlusOne)

plusOneNums = [2, 3, 4, 5, 6, 7]
oddNums =  [1, 3, 5]
oddNumsPlusOn =  [2, 4, 6]


In [27]:
import numpy as np

In [28]:
A = np.array([1, 2, 3, 4, 5])
A

array([1, 2, 3, 4, 5])

In [29]:
L = [1, 2, 3, 4, 5, 6]

A = np.array(L)
A

array([1, 2, 3, 4, 5, 6])

In [30]:
A / 5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2])

In [31]:
np.array([1.0, 2, 3, 4, 5]) / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [32]:
M = np.array([2, 3, 4, 5, 6, 7])

P = L * M
P

array([ 2,  6, 12, 20, 30, 42])

In [33]:
P.sum()

112

In [34]:
P.mean()

18.666666666666668

In [35]:
np.dot(L, M)

112

In [36]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [8, 7, 6]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [8, 7, 6]])

In [37]:
A.shape

(4, 3)

In [38]:
A[0, 1]

2

In [39]:
A[2, 1]

8

In [40]:
A[:,1]

array([2, 5, 8, 7])

In [41]:
A[0,:]

array([1, 2, 3])

In [42]:
A[1:,1:]

array([[5, 6],
       [8, 9],
       [7, 6]])

In [43]:
A[1:3,1:]

array([[5, 6],
       [8, 9]])

In [44]:
A[1:,0:2]

array([[4, 5],
       [7, 8],
       [8, 7]])

In [45]:
A[-1,:]

array([8, 7, 6])

In [46]:
print(A)
print()
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [8 7 6]]

[[1 4 7 8]
 [2 5 8 7]
 [3 6 9 6]]


In [47]:
C = np.array([1, 10, 20])

print("A: \n", A)
print()
print("C: \n", C)
print()
print("A * C: \n", A * C)
print()
print("A dot C: \n", np.dot(A, C))

A: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [8 7 6]]

C: 
 [ 1 10 20]

A * C: 
 [[  1  20  60]
 [  4  50 120]
 [  7  80 180]
 [  8  70 120]]

A dot C: 
 [ 81 174 267 198]


In [48]:
A = np.mat(A)
C = np.mat(C)

print(A * C.T)

[[ 81]
 [174]
 [267]
 [198]]


In [49]:
print("C Transpose: \n", C.T)
print()
print("A * C: \n",A * C.T)

C Transpose: 
 [[ 1]
 [10]
 [20]]

A * C: 
 [[ 81]
 [174]
 [267]
 [198]]


In [50]:
A = np.array([1, 2, 3, 4, 5, 6])
A > 3

array([False, False, False,  True,  True,  True])

In [51]:
A[A > 3]

array([4, 5, 6])

In [52]:
sum(A[A > 3])

15

In [53]:
Ind = (A > 1) & (A < 6)
print(Ind)
A[Ind]

[False  True  True  True  True False]


array([2, 3, 4, 5])